// flow-typed signature: 2465377a23037ace957bf9410ae7541e
// flow-typed version: <<STUB>>/expo-font_v^11.10.3/flow_v0.235.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-font'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-font' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-font/app.plugin' {
  declare module.exports: any;
}

declare module 'expo-font/build/ExpoFontLoader' {
  declare module.exports: any;
}

declare module 'expo-font/build/ExpoFontLoader.web' {
  declare module.exports: any;
}

declare module 'expo-font/build/Font' {
  declare module.exports: any;
}

declare module 'expo-font/build/Font.types' {
  declare module.exports: any;
}

declare module 'expo-font/build/FontHooks' {
  declare module.exports: any;
}

declare module 'expo-font/build/FontLoader' {
  declare module.exports: any;
}

declare module 'expo-font/build/FontLoader.web' {
  declare module.exports: any;
}

declare module 'expo-font/build' {
  declare module.exports: any;
}

declare module 'expo-font/build/memory' {
  declare module.exports: any;
}

declare module 'expo-font/build/server' {
  declare module.exports: any;
}

declare module 'expo-font/plugin/build/utils' {
  declare module.exports: any;
}

declare module 'expo-font/plugin/build/withFonts' {
  declare module.exports: any;
}

declare module 'expo-font/plugin/build/withFontsAndroid' {
  declare module.exports: any;
}

declare module 'expo-font/plugin/build/withFontsIos' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-font/app.plugin.js' {
  declare module.exports: $Exports<'expo-font/app.plugin'>;
}
declare module 'expo-font/build/ExpoFontLoader.js' {
  declare module.exports: $Exports<'expo-font/build/ExpoFontLoader'>;
}
declare module 'expo-font/build/ExpoFontLoader.web.js' {
  declare module.exports: $Exports<'expo-font/build/ExpoFontLoader.web'>;
}
declare module 'expo-font/build/Font.js' {
  declare module.exports: $Exports<'expo-font/build/Font'>;
}
declare module 'expo-font/build/Font.types.js' {
  declare module.exports: $Exports<'expo-font/build/Font.types'>;
}
declare module 'expo-font/build/FontHooks.js' {
  declare module.exports: $Exports<'expo-font/build/FontHooks'>;
}
declare module 'expo-font/build/FontLoader.js' {
  declare module.exports: $Exports<'expo-font/build/FontLoader'>;
}
declare module 'expo-font/build/FontLoader.web.js' {
  declare module.exports: $Exports<'expo-font/build/FontLoader.web'>;
}
declare module 'expo-font/build/index' {
  declare module.exports: $Exports<'expo-font/build'>;
}
declare module 'expo-font/build/index.js' {
  declare module.exports: $Exports<'expo-font/build'>;
}
declare module 'expo-font/build/memory.js' {
  declare module.exports: $Exports<'expo-font/build/memory'>;
}
declare module 'expo-font/build/server.js' {
  declare module.exports: $Exports<'expo-font/build/server'>;
}
declare module 'expo-font/plugin/build/utils.js' {
  declare module.exports: $Exports<'expo-font/plugin/build/utils'>;
}
declare module 'expo-font/plugin/build/withFonts.js' {
  declare module.exports: $Exports<'expo-font/plugin/build/withFonts'>;
}
declare module 'expo-font/plugin/build/withFontsAndroid.js' {
  declare module.exports: $Exports<'expo-font/plugin/build/withFontsAndroid'>;
}
declare module 'expo-font/plugin/build/withFontsIos.js' {
  declare module.exports: $Exports<'expo-font/plugin/build/withFontsIos'>;
}
