// flow-typed signature: 797cdfb40fd6538fc9ffda8413155c4a
// flow-typed version: <<STUB>>/expo_v~50.0.14/flow_v0.235.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo/AppEntry' {
  declare module.exports: any;
}

declare module 'expo/build/devtools/devtools.types' {
  declare module.exports: any;
}

declare module 'expo/build/devtools/DevToolsPluginClient' {
  declare module.exports: any;
}

declare module 'expo/build/devtools/DevToolsPluginClientFactory' {
  declare module.exports: any;
}

declare module 'expo/build/devtools/DevToolsPluginClientImplApp' {
  declare module.exports: any;
}

declare module 'expo/build/devtools/DevToolsPluginClientImplBrowser' {
  declare module.exports: any;
}

declare module 'expo/build/devtools/getConnectionInfo' {
  declare module.exports: any;
}

declare module 'expo/build/devtools/getConnectionInfo.native' {
  declare module.exports: any;
}

declare module 'expo/build/devtools' {
  declare module.exports: any;
}

declare module 'expo/build/devtools/logger' {
  declare module.exports: any;
}

declare module 'expo/build/devtools/WebSocketBackingStore' {
  declare module.exports: any;
}

declare module 'expo/build/devtools/WebSocketWithReconnect' {
  declare module.exports: any;
}

declare module 'expo/build/environment/DevLoadingView' {
  declare module.exports: any;
}

declare module 'expo/build/environment/DevLoadingViewNativeModule' {
  declare module.exports: any;
}

declare module 'expo/build/environment/DevLoadingViewNativeModule.native' {
  declare module.exports: any;
}

declare module 'expo/build/environment/ExpoGo' {
  declare module.exports: any;
}

declare module 'expo/build/environment/ExpoGo.web' {
  declare module.exports: any;
}

declare module 'expo/build/environment/getInitialSafeArea' {
  declare module.exports: any;
}

declare module 'expo/build/environment/getInitialSafeArea.native' {
  declare module.exports: any;
}

declare module 'expo/build/errors/ExpoErrorManager' {
  declare module.exports: any;
}

declare module 'expo/build/errors/ExpoErrorManager.native' {
  declare module.exports: any;
}

declare module 'expo/build/Expo.fx' {
  declare module.exports: any;
}

declare module 'expo/build/Expo.fx.web' {
  declare module.exports: any;
}

declare module 'expo/build/Expo' {
  declare module.exports: any;
}

declare module 'expo/build/launch/registerRootComponent' {
  declare module.exports: any;
}

declare module 'expo/build/launch/withDevTools.ios' {
  declare module.exports: any;
}

declare module 'expo/build/launch/withDevTools' {
  declare module.exports: any;
}

declare module 'expo/build/launch/withDevTools.web' {
  declare module.exports: any;
}

declare module 'expo/build/timer/polyfillNextTick' {
  declare module.exports: any;
}

declare module 'expo/build/winter' {
  declare module.exports: any;
}

declare module 'expo/build/winter/runtime' {
  declare module.exports: any;
}

declare module 'expo/build/winter/runtime.native' {
  declare module.exports: any;
}

declare module 'expo/build/winter/url' {
  declare module.exports: any;
}

declare module 'expo/config-plugins' {
  declare module.exports: any;
}

declare module 'expo/config' {
  declare module.exports: any;
}

declare module 'expo/devtools' {
  declare module.exports: any;
}

declare module 'expo/metro-config' {
  declare module.exports: any;
}

declare module 'expo/react-native.config' {
  declare module.exports: any;
}

declare module 'expo/scripts/compose-source-maps' {
  declare module.exports: any;
}

declare module 'expo/scripts/resolveAppEntry' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo/AppEntry.js' {
  declare module.exports: $Exports<'expo/AppEntry'>;
}
declare module 'expo/build/devtools/devtools.types.js' {
  declare module.exports: $Exports<'expo/build/devtools/devtools.types'>;
}
declare module 'expo/build/devtools/DevToolsPluginClient.js' {
  declare module.exports: $Exports<'expo/build/devtools/DevToolsPluginClient'>;
}
declare module 'expo/build/devtools/DevToolsPluginClientFactory.js' {
  declare module.exports: $Exports<'expo/build/devtools/DevToolsPluginClientFactory'>;
}
declare module 'expo/build/devtools/DevToolsPluginClientImplApp.js' {
  declare module.exports: $Exports<'expo/build/devtools/DevToolsPluginClientImplApp'>;
}
declare module 'expo/build/devtools/DevToolsPluginClientImplBrowser.js' {
  declare module.exports: $Exports<'expo/build/devtools/DevToolsPluginClientImplBrowser'>;
}
declare module 'expo/build/devtools/getConnectionInfo.js' {
  declare module.exports: $Exports<'expo/build/devtools/getConnectionInfo'>;
}
declare module 'expo/build/devtools/getConnectionInfo.native.js' {
  declare module.exports: $Exports<'expo/build/devtools/getConnectionInfo.native'>;
}
declare module 'expo/build/devtools/index' {
  declare module.exports: $Exports<'expo/build/devtools'>;
}
declare module 'expo/build/devtools/index.js' {
  declare module.exports: $Exports<'expo/build/devtools'>;
}
declare module 'expo/build/devtools/logger.js' {
  declare module.exports: $Exports<'expo/build/devtools/logger'>;
}
declare module 'expo/build/devtools/WebSocketBackingStore.js' {
  declare module.exports: $Exports<'expo/build/devtools/WebSocketBackingStore'>;
}
declare module 'expo/build/devtools/WebSocketWithReconnect.js' {
  declare module.exports: $Exports<'expo/build/devtools/WebSocketWithReconnect'>;
}
declare module 'expo/build/environment/DevLoadingView.js' {
  declare module.exports: $Exports<'expo/build/environment/DevLoadingView'>;
}
declare module 'expo/build/environment/DevLoadingViewNativeModule.js' {
  declare module.exports: $Exports<'expo/build/environment/DevLoadingViewNativeModule'>;
}
declare module 'expo/build/environment/DevLoadingViewNativeModule.native.js' {
  declare module.exports: $Exports<'expo/build/environment/DevLoadingViewNativeModule.native'>;
}
declare module 'expo/build/environment/ExpoGo.js' {
  declare module.exports: $Exports<'expo/build/environment/ExpoGo'>;
}
declare module 'expo/build/environment/ExpoGo.web.js' {
  declare module.exports: $Exports<'expo/build/environment/ExpoGo.web'>;
}
declare module 'expo/build/environment/getInitialSafeArea.js' {
  declare module.exports: $Exports<'expo/build/environment/getInitialSafeArea'>;
}
declare module 'expo/build/environment/getInitialSafeArea.native.js' {
  declare module.exports: $Exports<'expo/build/environment/getInitialSafeArea.native'>;
}
declare module 'expo/build/errors/ExpoErrorManager.js' {
  declare module.exports: $Exports<'expo/build/errors/ExpoErrorManager'>;
}
declare module 'expo/build/errors/ExpoErrorManager.native.js' {
  declare module.exports: $Exports<'expo/build/errors/ExpoErrorManager.native'>;
}
declare module 'expo/build/Expo.fx.js' {
  declare module.exports: $Exports<'expo/build/Expo.fx'>;
}
declare module 'expo/build/Expo.fx.web.js' {
  declare module.exports: $Exports<'expo/build/Expo.fx.web'>;
}
declare module 'expo/build/Expo.js' {
  declare module.exports: $Exports<'expo/build/Expo'>;
}
declare module 'expo/build/launch/registerRootComponent.js' {
  declare module.exports: $Exports<'expo/build/launch/registerRootComponent'>;
}
declare module 'expo/build/launch/withDevTools.ios.js' {
  declare module.exports: $Exports<'expo/build/launch/withDevTools.ios'>;
}
declare module 'expo/build/launch/withDevTools.js' {
  declare module.exports: $Exports<'expo/build/launch/withDevTools'>;
}
declare module 'expo/build/launch/withDevTools.web.js' {
  declare module.exports: $Exports<'expo/build/launch/withDevTools.web'>;
}
declare module 'expo/build/timer/polyfillNextTick.js' {
  declare module.exports: $Exports<'expo/build/timer/polyfillNextTick'>;
}
declare module 'expo/build/winter/index' {
  declare module.exports: $Exports<'expo/build/winter'>;
}
declare module 'expo/build/winter/index.js' {
  declare module.exports: $Exports<'expo/build/winter'>;
}
declare module 'expo/build/winter/runtime.js' {
  declare module.exports: $Exports<'expo/build/winter/runtime'>;
}
declare module 'expo/build/winter/runtime.native.js' {
  declare module.exports: $Exports<'expo/build/winter/runtime.native'>;
}
declare module 'expo/build/winter/url.js' {
  declare module.exports: $Exports<'expo/build/winter/url'>;
}
declare module 'expo/config-plugins.js' {
  declare module.exports: $Exports<'expo/config-plugins'>;
}
declare module 'expo/config.js' {
  declare module.exports: $Exports<'expo/config'>;
}
declare module 'expo/devtools.js' {
  declare module.exports: $Exports<'expo/devtools'>;
}
declare module 'expo/metro-config.js' {
  declare module.exports: $Exports<'expo/metro-config'>;
}
declare module 'expo/react-native.config.js' {
  declare module.exports: $Exports<'expo/react-native.config'>;
}
declare module 'expo/scripts/compose-source-maps.js' {
  declare module.exports: $Exports<'expo/scripts/compose-source-maps'>;
}
declare module 'expo/scripts/resolveAppEntry.js' {
  declare module.exports: $Exports<'expo/scripts/resolveAppEntry'>;
}
