// flow-typed signature: bfc57a9ba004a9d7c3369ae29f3ffd20
// flow-typed version: <<STUB>>/react-native-reanimated_v~3.6.2/flow_v0.235.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-reanimated'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-reanimated' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-reanimated/lib/module/Animated' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/animationBuilder' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/ConfigHelper' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/createAnimatedComponent/commonTypes' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/createAnimatedComponent/createAnimatedComponent' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/createAnimatedComponent' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/createAnimatedComponent/InlinePropManager' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/createAnimatedComponent/JSPropsUpdater' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/createAnimatedComponent/PropsFilter' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/createAnimatedComponent/setAndForwardRef' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/createAnimatedComponent/utils' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/index.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/propsAllowlists' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/animation/clamp' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/animation/commonTypes' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/animation/decay/decay' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/animation/decay' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/animation/decay/rigidDecay' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/animation/decay/rubberBandDecay' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/animation/decay/utils' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/animation/delay' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/animation' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/animation/repeat' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/animation/sequence' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/animation/spring' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/animation/springUtils' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/animation/styleAnimation' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/animation/timing' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/animation/transformationMatrix/matrixUtils' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/animation/util' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/Bezier' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/Colors' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/commonTypes' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/component/FlatList' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/component/Image' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/component/LayoutAnimationConfig' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/component/ScrollView' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/component/Text' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/component/View' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/core' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/Easing' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/errors' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/fabricUtils' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/fabricUtils.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/frameCallback/FrameCallbackRegistryJS' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/frameCallback/FrameCallbackRegistryUI' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/frameCallback' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/globals.d' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/helperTypes' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/commonTypes' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedKeyboard' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedProps' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedReaction' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedRef' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedScrollHandler' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedSensor' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedStyle' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/useDerivedValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/useEvent' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/useFrameCallback' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/useHandler' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/useReducedMotion' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/useScrollViewOffset' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/useSharedValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/useWorkletCallback' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/hook/utils' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/initializers' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/interpolateColor' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/interpolation' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/isSharedValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/jestUtils' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/jestUtils.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/js-reanimated' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/js-reanimated/JSReanimated' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/js-reanimated/react-native-web.d' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/js-reanimated/WebSensor' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationBuilder/BaseAnimationBuilder' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationBuilder/commonTypes' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationBuilder/ComplexAnimationBuilder' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationBuilder' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationBuilder/Keyframe' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationsManager' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Bounce' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Fade' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Flip' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Lightspeed' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Pinwheel' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Roll' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Rotate' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Slide' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Stretch' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Zoom' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/CurvedTransition' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/EntryExitTransition' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/FadingTransition' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/JumpingTransition' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/LinearTransition' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/SequencedTransition' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/sharedTransitions' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/sharedTransitions/ProgressTransitionManager' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/sharedTransitions/SharedTransition' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/sharedTransitions/SharedTransition.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Bounce.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Fade.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Flip.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Lightspeed.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Pinwheel.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Roll.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Rotate.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Slide.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Stretch.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Zoom.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animationParser' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animationsManager' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/componentUtils' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/config' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/createAnimation' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/domUtils' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/transition/Fading.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/transition/Linear.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/transition/Sequenced.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/mappers' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/mock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/mockedRequestAnimationFrame' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/mutables' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/NativeReanimated' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/NativeReanimated/index.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/NativeReanimated/NativeReanimated' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/platform-specific/checkCppVersion' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/platform-specific/jsVersion' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/platform-specific/RNRenderer' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/platform-specific/RNRenderer.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/PlatformChecker' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/dispatchCommand' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/dispatchCommand.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/getRelativeCoords' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/measure' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/measure.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/scrollTo' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/scrollTo.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/setGestureState' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/setGestureState.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/setNativeProps' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/setNativeProps.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/pluginUtils' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/PropAdapters' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/PropsRegistry' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/publicGlobals' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/runtimes' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/Sensor' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/SensorContainer' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/shareables' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/threads' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/UpdateProps' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/valueSetter' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/valueUnpacker' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/ViewDescriptorsSet' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/reanimated2/WorkletEventHandler' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/mock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/plugin/build/plugin' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-reanimated/lib/module/Animated.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/Animated'>;
}
declare module 'react-native-reanimated/lib/module/animationBuilder.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/animationBuilder'>;
}
declare module 'react-native-reanimated/lib/module/ConfigHelper.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/ConfigHelper'>;
}
declare module 'react-native-reanimated/lib/module/createAnimatedComponent/commonTypes.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/createAnimatedComponent/commonTypes'>;
}
declare module 'react-native-reanimated/lib/module/createAnimatedComponent/createAnimatedComponent.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/createAnimatedComponent/createAnimatedComponent'>;
}
declare module 'react-native-reanimated/lib/module/createAnimatedComponent/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/createAnimatedComponent'>;
}
declare module 'react-native-reanimated/lib/module/createAnimatedComponent/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/createAnimatedComponent'>;
}
declare module 'react-native-reanimated/lib/module/createAnimatedComponent/InlinePropManager.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/createAnimatedComponent/InlinePropManager'>;
}
declare module 'react-native-reanimated/lib/module/createAnimatedComponent/JSPropsUpdater.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/createAnimatedComponent/JSPropsUpdater'>;
}
declare module 'react-native-reanimated/lib/module/createAnimatedComponent/PropsFilter.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/createAnimatedComponent/PropsFilter'>;
}
declare module 'react-native-reanimated/lib/module/createAnimatedComponent/setAndForwardRef.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/createAnimatedComponent/setAndForwardRef'>;
}
declare module 'react-native-reanimated/lib/module/createAnimatedComponent/utils.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/createAnimatedComponent/utils'>;
}
declare module 'react-native-reanimated/lib/module/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module'>;
}
declare module 'react-native-reanimated/lib/module/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module'>;
}
declare module 'react-native-reanimated/lib/module/index.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/index.web'>;
}
declare module 'react-native-reanimated/lib/module/propsAllowlists.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/propsAllowlists'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/clamp.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation/clamp'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/commonTypes.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation/commonTypes'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/decay/decay.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation/decay/decay'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/decay/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation/decay'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/decay/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation/decay'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/decay/rigidDecay.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation/decay/rigidDecay'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/decay/rubberBandDecay.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation/decay/rubberBandDecay'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/decay/utils.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation/decay/utils'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/delay.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation/delay'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/repeat.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation/repeat'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/sequence.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation/sequence'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/spring.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation/spring'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/springUtils.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation/springUtils'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/styleAnimation.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation/styleAnimation'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/timing.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation/timing'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/transformationMatrix/matrixUtils.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation/transformationMatrix/matrixUtils'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/animation/util.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/animation/util'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/Bezier.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/Bezier'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/Colors.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/Colors'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/commonTypes.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/commonTypes'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/component/FlatList.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/component/FlatList'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/component/Image.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/component/Image'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/component/LayoutAnimationConfig.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/component/LayoutAnimationConfig'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/component/ScrollView.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/component/ScrollView'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/component/Text.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/component/Text'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/component/View.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/component/View'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/core.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/core'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/Easing.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/Easing'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/errors.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/errors'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/fabricUtils.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/fabricUtils'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/fabricUtils.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/fabricUtils.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/frameCallback/FrameCallbackRegistryJS.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/frameCallback/FrameCallbackRegistryJS'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/frameCallback/FrameCallbackRegistryUI.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/frameCallback/FrameCallbackRegistryUI'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/frameCallback/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/frameCallback'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/frameCallback/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/frameCallback'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/globals.d.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/globals.d'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/helperTypes.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/helperTypes'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/commonTypes.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/commonTypes'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedGestureHandler.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedGestureHandler'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedKeyboard.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedKeyboard'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedProps.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedProps'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedReaction.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedReaction'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedRef.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedRef'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedScrollHandler.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedScrollHandler'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedSensor.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedSensor'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedStyle.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/useAnimatedStyle'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/useDerivedValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/useDerivedValue'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/useEvent.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/useEvent'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/useFrameCallback.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/useFrameCallback'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/useHandler.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/useHandler'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/useReducedMotion.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/useReducedMotion'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/useScrollViewOffset.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/useScrollViewOffset'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/useSharedValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/useSharedValue'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/useWorkletCallback.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/useWorkletCallback'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/hook/utils.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/hook/utils'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/initializers.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/initializers'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/interpolateColor.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/interpolateColor'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/interpolation.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/interpolation'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/isSharedValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/isSharedValue'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/jestUtils.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/jestUtils'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/jestUtils.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/jestUtils.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/js-reanimated/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/js-reanimated'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/js-reanimated/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/js-reanimated'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/js-reanimated/JSReanimated.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/js-reanimated/JSReanimated'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/js-reanimated/react-native-web.d.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/js-reanimated/react-native-web.d'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/js-reanimated/WebSensor.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/js-reanimated/WebSensor'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationBuilder/BaseAnimationBuilder.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationBuilder/BaseAnimationBuilder'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationBuilder/commonTypes.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationBuilder/commonTypes'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationBuilder/ComplexAnimationBuilder.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationBuilder/ComplexAnimationBuilder'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationBuilder/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationBuilder'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationBuilder/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationBuilder'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationBuilder/Keyframe.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationBuilder/Keyframe'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationsManager.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/animationsManager'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Bounce.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Bounce'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Fade.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Fade'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Flip.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Flip'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Lightspeed.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Lightspeed'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Pinwheel.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Pinwheel'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Roll.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Roll'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Rotate.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Rotate'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Slide.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Slide'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Stretch.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Stretch'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Zoom.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultAnimations/Zoom'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/CurvedTransition.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/CurvedTransition'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/EntryExitTransition.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/EntryExitTransition'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/FadingTransition.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/FadingTransition'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/JumpingTransition.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/JumpingTransition'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/LinearTransition.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/LinearTransition'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/SequencedTransition.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/defaultTransitions/SequencedTransition'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/sharedTransitions/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/sharedTransitions'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/sharedTransitions/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/sharedTransitions'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/sharedTransitions/ProgressTransitionManager.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/sharedTransitions/ProgressTransitionManager'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/sharedTransitions/SharedTransition.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/sharedTransitions/SharedTransition'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/sharedTransitions/SharedTransition.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/sharedTransitions/SharedTransition.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Bounce.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Bounce.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Fade.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Fade.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Flip.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Flip.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Lightspeed.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Lightspeed.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Pinwheel.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Pinwheel.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Roll.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Roll.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Rotate.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Rotate.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Slide.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Slide.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Stretch.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Stretch.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Zoom.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animation/Zoom.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animationParser.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animationParser'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animationsManager.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/animationsManager'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/componentUtils.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/componentUtils'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/config.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/config'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/createAnimation.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/createAnimation'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/domUtils.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/domUtils'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/transition/Fading.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/transition/Fading.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/transition/Linear.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/transition/Linear.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/transition/Sequenced.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/layoutReanimation/web/transition/Sequenced.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/mappers.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/mappers'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/mock.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/mock'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/mockedRequestAnimationFrame.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/mockedRequestAnimationFrame'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/mutables.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/mutables'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/NativeReanimated/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/NativeReanimated'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/NativeReanimated/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/NativeReanimated'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/NativeReanimated/index.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/NativeReanimated/index.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/NativeReanimated/NativeReanimated.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/NativeReanimated/NativeReanimated'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/platform-specific/checkCppVersion.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/platform-specific/checkCppVersion'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/platform-specific/jsVersion.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/platform-specific/jsVersion'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/platform-specific/RNRenderer.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/platform-specific/RNRenderer'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/platform-specific/RNRenderer.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/platform-specific/RNRenderer.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/PlatformChecker.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/PlatformChecker'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/dispatchCommand.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/platformFunctions/dispatchCommand'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/dispatchCommand.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/platformFunctions/dispatchCommand.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/getRelativeCoords.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/platformFunctions/getRelativeCoords'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/platformFunctions'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/platformFunctions'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/measure.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/platformFunctions/measure'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/measure.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/platformFunctions/measure.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/scrollTo.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/platformFunctions/scrollTo'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/scrollTo.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/platformFunctions/scrollTo.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/setGestureState.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/platformFunctions/setGestureState'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/setGestureState.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/platformFunctions/setGestureState.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/setNativeProps.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/platformFunctions/setNativeProps'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/platformFunctions/setNativeProps.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/platformFunctions/setNativeProps.web'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/pluginUtils.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/pluginUtils'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/PropAdapters.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/PropAdapters'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/PropsRegistry.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/PropsRegistry'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/publicGlobals.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/publicGlobals'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/runtimes.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/runtimes'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/Sensor.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/Sensor'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/SensorContainer.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/SensorContainer'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/shareables.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/shareables'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/threads.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/threads'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/UpdateProps.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/UpdateProps'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/valueSetter.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/valueSetter'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/valueUnpacker.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/valueUnpacker'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/ViewDescriptorsSet.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/ViewDescriptorsSet'>;
}
declare module 'react-native-reanimated/lib/module/reanimated2/WorkletEventHandler.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/reanimated2/WorkletEventHandler'>;
}
declare module 'react-native-reanimated/mock.js' {
  declare module.exports: $Exports<'react-native-reanimated/mock'>;
}
declare module 'react-native-reanimated/plugin/build/plugin.js' {
  declare module.exports: $Exports<'react-native-reanimated/plugin/build/plugin'>;
}
declare module 'react-native-reanimated/plugin/index' {
  declare module.exports: $Exports<'react-native-reanimated/plugin'>;
}
declare module 'react-native-reanimated/plugin/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/plugin'>;
}
