// flow-typed signature: 8e099369616192d83eb8d8af67367214
// flow-typed version: <<STUB>>/react-native-draggable-flatlist_v^4.0.1/flow_v0.235.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-draggable-flatlist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-draggable-flatlist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-draggable-flatlist/babel.config' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/jest-setup' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/components/CellDecorators' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/components/CellRendererComponent' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/components/DraggableFlatList' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/components/NestableDraggableFlatList' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/components/NestableScrollContainer' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/components/PlaceholderItem' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/components/RowItem' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/components/ScrollOffsetListener' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/constants' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/context/animatedValueContext' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/context/cellContext' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/context/draggableFlatListContext' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/context/nestableScrollContainerContext' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/context/propsContext' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/context/refContext' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/hooks/useAutoScroll' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/hooks/useCellTranslate' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/hooks/useNestedAutoScroll' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/hooks/useOnCellActiveAnimation' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/hooks/useStableCallback' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/types' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/commonjs/utils' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/components/CellDecorators' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/components/CellRendererComponent' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/components/DraggableFlatList' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/components/NestableDraggableFlatList' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/components/NestableScrollContainer' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/components/PlaceholderItem' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/components/RowItem' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/components/ScrollOffsetListener' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/constants' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/context/animatedValueContext' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/context/cellContext' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/context/draggableFlatListContext' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/context/nestableScrollContainerContext' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/context/propsContext' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/context/refContext' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/hooks/useAutoScroll' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/hooks/useCellTranslate' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/hooks/useNestedAutoScroll' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/hooks/useOnCellActiveAnimation' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/hooks/useStableCallback' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/types' {
  declare module.exports: any;
}

declare module 'react-native-draggable-flatlist/lib/module/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-draggable-flatlist/babel.config.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/babel.config'>;
}
declare module 'react-native-draggable-flatlist/jest-setup.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/jest-setup'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/components/CellDecorators.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/components/CellDecorators'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/components/CellRendererComponent.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/components/CellRendererComponent'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/components/DraggableFlatList.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/components/DraggableFlatList'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/components/NestableDraggableFlatList.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/components/NestableDraggableFlatList'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/components/NestableScrollContainer.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/components/NestableScrollContainer'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/components/PlaceholderItem.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/components/PlaceholderItem'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/components/RowItem.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/components/RowItem'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/components/ScrollOffsetListener.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/components/ScrollOffsetListener'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/constants.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/constants'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/context/animatedValueContext.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/context/animatedValueContext'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/context/cellContext.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/context/cellContext'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/context/draggableFlatListContext.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/context/draggableFlatListContext'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/context/nestableScrollContainerContext.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/context/nestableScrollContainerContext'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/context/propsContext.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/context/propsContext'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/context/refContext.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/context/refContext'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/hooks/useAutoScroll.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/hooks/useAutoScroll'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/hooks/useCellTranslate.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/hooks/useCellTranslate'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/hooks/useNestedAutoScroll.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/hooks/useNestedAutoScroll'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/hooks/useOnCellActiveAnimation.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/hooks/useOnCellActiveAnimation'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/hooks/useStableCallback.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/hooks/useStableCallback'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/index' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/index.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/types.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/types'>;
}
declare module 'react-native-draggable-flatlist/lib/commonjs/utils.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/commonjs/utils'>;
}
declare module 'react-native-draggable-flatlist/lib/module/components/CellDecorators.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/components/CellDecorators'>;
}
declare module 'react-native-draggable-flatlist/lib/module/components/CellRendererComponent.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/components/CellRendererComponent'>;
}
declare module 'react-native-draggable-flatlist/lib/module/components/DraggableFlatList.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/components/DraggableFlatList'>;
}
declare module 'react-native-draggable-flatlist/lib/module/components/NestableDraggableFlatList.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/components/NestableDraggableFlatList'>;
}
declare module 'react-native-draggable-flatlist/lib/module/components/NestableScrollContainer.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/components/NestableScrollContainer'>;
}
declare module 'react-native-draggable-flatlist/lib/module/components/PlaceholderItem.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/components/PlaceholderItem'>;
}
declare module 'react-native-draggable-flatlist/lib/module/components/RowItem.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/components/RowItem'>;
}
declare module 'react-native-draggable-flatlist/lib/module/components/ScrollOffsetListener.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/components/ScrollOffsetListener'>;
}
declare module 'react-native-draggable-flatlist/lib/module/constants.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/constants'>;
}
declare module 'react-native-draggable-flatlist/lib/module/context/animatedValueContext.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/context/animatedValueContext'>;
}
declare module 'react-native-draggable-flatlist/lib/module/context/cellContext.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/context/cellContext'>;
}
declare module 'react-native-draggable-flatlist/lib/module/context/draggableFlatListContext.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/context/draggableFlatListContext'>;
}
declare module 'react-native-draggable-flatlist/lib/module/context/nestableScrollContainerContext.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/context/nestableScrollContainerContext'>;
}
declare module 'react-native-draggable-flatlist/lib/module/context/propsContext.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/context/propsContext'>;
}
declare module 'react-native-draggable-flatlist/lib/module/context/refContext.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/context/refContext'>;
}
declare module 'react-native-draggable-flatlist/lib/module/hooks/useAutoScroll.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/hooks/useAutoScroll'>;
}
declare module 'react-native-draggable-flatlist/lib/module/hooks/useCellTranslate.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/hooks/useCellTranslate'>;
}
declare module 'react-native-draggable-flatlist/lib/module/hooks/useNestedAutoScroll.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/hooks/useNestedAutoScroll'>;
}
declare module 'react-native-draggable-flatlist/lib/module/hooks/useOnCellActiveAnimation.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/hooks/useOnCellActiveAnimation'>;
}
declare module 'react-native-draggable-flatlist/lib/module/hooks/useStableCallback.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/hooks/useStableCallback'>;
}
declare module 'react-native-draggable-flatlist/lib/module/index' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module'>;
}
declare module 'react-native-draggable-flatlist/lib/module/index.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module'>;
}
declare module 'react-native-draggable-flatlist/lib/module/types.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/types'>;
}
declare module 'react-native-draggable-flatlist/lib/module/utils.js' {
  declare module.exports: $Exports<'react-native-draggable-flatlist/lib/module/utils'>;
}
